### ISSUE TITLE
Plugshare?

### ISSUE THREAD

**Issue by EasternPA** [rickbassham/tesla-dashboard#84]
Has plugshare blocked an API call from you? I'm super close to buying a Model 3 and was checking out your (awesome) dashboard. The Plugshare panel doesn't load for me in Chrome on Windows. I'm wondering if they blocked your API call method.

Thanks!

**Comment by rickbassham** [comment]
Yeah, looks like they are blocking being able to frame in their site. :(

**Comment by EasternPA** [comment]
Okay just checking. Great job, btw. Shame about Plugshare.
